//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateTeamText {
            get {
                return ResourceManager.GetString("CreateTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input team name.
        /// </summary>
        internal static string InputTeamNameMessage {
            get {
                return ResourceManager.GetString("InputTeamNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string JoinTeamText {
            get {
                return ResourceManager.GetString("JoinTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to play in the team.
        /// </summary>
        internal static string MultiPlayerTeam {
            get {
                return ResourceManager.GetString("MultiPlayerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to play alone.
        /// </summary>
        internal static string OnePlayerTeam {
            get {
                return ResourceManager.GetString("OnePlayerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an option from the list..
        /// </summary>
        internal static string RetryPromptText {
            get {
                return ResourceManager.GetString("RetryPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want join to team or create own team?.
        /// </summary>
        internal static string SelectTeamText {
            get {
                return ResourceManager.GetString("SelectTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you want to play.
        /// </summary>
        internal static string SelectTeamTypeText {
            get {
                return ResourceManager.GetString("SelectTeamTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &apos;{0}&apos; is alread exits. Please enter another name..
        /// </summary>
        internal static string TeamAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("TeamAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &apos;{0}&apos; not found..
        /// </summary>
        internal static string TeamNotFoundMessage {
            get {
                return ResourceManager.GetString("TeamNotFoundMessage", resourceCulture);
            }
        }
    }
}
